# Generated by Django 4.2.7 on 2023-11-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('materia', models.CharField(choices=[('Programación lógica', 'Programación lógica'), ('Licenciatura en informática', (('Algebra', 'Algebra'), ('Programación Orientada a Objetos', 'Programación Orientada a Objetos'))), ('Licenciatura en economía', (('Administración I', 'Administración I'), ('Contabilidad', 'Contabilidad'), ('Principios de economía', 'Principios de economía'))), ('Abogacía', (('Introducción al derecho', 'Introducción al derecho'), ('Teoría de la Persona', 'Teoría de la Persona'), ('Derecho Penal I', 'Derecho Penal I')))], max_length=100)),
            ],
        ),
    ]
